[package]
name = "pyrunner"
version = "0.1.0"
edition = "2024"

[dependencies.pyo3]
version = "0.27.2"
# Enabling this cargo feature will cause PyO3 to start a Python interpreter on first call to `Python::attach`
features = ["auto-initialize"]